### ISSUE TITLE
How to build from source use lazarus

### ISSUE THREAD

**Issue by junjunwang2016** [Noso-Project/nosoearn#1]
I'm not familiar with lazarus. Can you give me a detailed tutorial

**Comment by T200proX7** [comment]
Would be interesting to have a instruction as I receive several errors, no matter on which system I try to compile it.

**Comment by GalayZloy** [comment]
I check it in the Ubuntu 22.04.2 LTC, Lazarus 2.2.0 + packages "indylaz", "LazUtils" and it compiled without errors.

**Comment by DevTeamNoso** [comment]
You can visit:
https://forum.lazarus.freepascal.org/
For lazarus specific support.
