### ISSUE TITLE
cant run on debian 11 (lastest)

### ISSUE THREAD

**Issue by makertronic** [Noso-Project/nosoearn#2]
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/85033212/232250204-2ae1495e-15a0-4868-8ac8-bb3a98b0d264.png">

**Comment by T200proX7** [comment]
You have to compile it on a device that uses this glibc version. If you don't know anything about it, it will be quite complicated. I have already been through this ordeal.

**Comment by DevTeamNoso** [comment]
Fixed.
