### ISSUE TITLE
Error on compilation for `arm-linux` and `x86_64-win64` on cross compile

### ISSUE THREAD

**Issue by gcarreno** [Noso-Project/nosoearn#6]
```
/home/gcarreno/Programming/Noso/nosoearn/consominer2unit.pas(881,5) Error: (4007) Ordinal expression expected
/home/gcarreno/Programming/Noso/nosoearn/consominer2unit.pas(881,5) Hint: (4080) Converting the operands to "Int64" before doing the subtract could prevent overflow errors.
```

Should use `High()` not `Length()`!
But if this is a dynamic array, the whole construct of:
```pas
var
  x: Int64;
begin
  for x:=0 to Length(MyArray)-1 do
  begin
    // code
  end;
end;
```
Is completely lost on me cuz the last index is never visited!!!

**Comment by gcarreno** [comment]
Looks like in some architectures, like `arm-linux` and my cross-compile from Linux to `x86_64-win64`, dynamic arrays do not work with `Int64` indexes...

I changed the code to:
```pas
var
  x: Integer;
begin
  for x:=Low(MyArray) to High(MyArray) do
  begin
    // code
  end;
end;
```

And now all is well !!!

**Comment by gcarreno** [comment]
The best way to avoid all this drama is to use the `for..in` loop:
```pas
var
  AvgRec: TAveEarning;
begin
  for AvgRec in Array_AveEarnings do
  begin
    // code
   // AvgRec.change, etc
  end;
end;
```
This is a lot more efficient also!!

**Comment by gcarreno** [comment]
Tested and works fine:
```pas
Function GetAverageEarnings():Int64;
var
  AveEarn: TAveEarning;
  valid,total, perblock :int64;
Begin
Result := 0;
valid := 0; total := 0;
for AveEarn in Array_AveEarns do
   begin
   if AveEarn.change>=0 then
      begin
      Inc(Valid);
      Inc(Total, AveEarn.change);
      end;
   end;
if valid>0 then PerBlock := Total div Valid
else PerBlock := 0;
Result := Perblock * 144;
End;
```

**Comment by gcarreno** [comment]
This page about the Ordinal types, explains why:
https://www.freepascal.org/docs-html/ref/refsu4.html

Mainly:
> Remark Int64 and QWord are considered ordinal types on 64-bit CPUs. On 32-bit types they have some of the characteristics of ordinals, ➡️but they cannot be used e. g. in for loops⬅️.

**Comment by DevTeamNoso** [comment]
**Length-1** actually checks the whole dynamic array.
Issue fixed using a **Integer** counter.
As for 32bit systems, project support stoped several months ago.

**Comment by gcarreno** [comment]
Hey Pedro (@DevTeamNoso)
> Length-1 actually checks the whole dynamic array.
Ooops, my bad. You are absolutely correct, sorry!

> Issue fixed using a Integer counter.
Awesome, THANKS!!

> As for 32bit systems, project support stopped several months ago.
I see that being the thing for Win32 and Linux 32.
The matter of fact is that there's still a lot of Raspberry Pi, especially the 3B+ ones that are running `arm-linux`, and that one is a 32b flavour.
Free Pascal's support of `aarch64` is still a bit iffy and therefore not yet enforceable.
Unless of course, you also decided that Raspberry Pi support has been dropped....

Cheers,
Gus
